openapi: 3.0.0
info:
  title: Market API
  description: Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/) or HTML.
  version: 0.1.9

servers:
  - url: http://localhost:5000
    description: Optional server description, e.g. Main (production) server
components:
  securitySchemes:
    ApiKeyAuth:     
      type: apiKey
      in: header     
      name: api-key
security:
  - ApiKeyAuth: []  

paths:
  /report/all:
    get:
      summary: Returns Report.
      description: Optional extended description in CommonMark or HTML.
      responses:
        '200':  
          description: A JSON array of user names
          content:
            application/json:
              schema: 
                type: array
                items: 
                  type: string
  /report:
    post:
      summary: Create Report.
      requestBody:
        required: true
        content:
          multipart/form-data:  
            schema:
              type: object
              properties:
                location:
                  type: string
                report:
                  type: string
                file:
                  type: string
      responses:
        '201':
          description: Created

  /market/all:
    get:
      summary: Returns Market.
      description: Optional extended description in CommonMark or HTML.
      security:
        - ApiKeyAuth: []  
      responses:
        '200':  
          description: A JSON array of user names
          content:
            application/json:
              schema: 
                type: array
                items: 
                  type: string

  /market/ToNotNull/{id}:
    put:
      summary: Update Market Places.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: integer
                status:
                  type: string
      responses: 
        '201':
          description: Updated
  /market/ToNull/{id}:
    put:
      summary: Update Market Places.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: integer
                status:
                  type: string
      responses: 
        '201':
          description: Updated
  /market/{key}:
    get:
      summary: Returns a Market by ID.
      parameters:
        - name: key
          in: path
          required: true
          description: Parameter description in CommonMark or HTML.
          schema:
            type : string
            minimum: 1
      responses: 
        '200':
          description: OK
    delete:
      summary: Delete a Market by ID.
      parameters:
        - name: id
          in: path
          required: true
          description: Parameter description in CommonMark or HTML.
          schema:
            type : integer
            format: int64
            minimum: 1
      responses: 
        '200':
          description: OK

  /stall/all:
    get:
      summary: Returns Market.
      description: Optional extended description in CommonMark or HTML.
      security:
        - ApiKeyAuth: []  
      responses:
        '200':  
          description: A JSON array of user names
          content:
            application/json:
              schema: 
                type: array
                items: 
                  type: string

